openapi: 3.2.0
info:
  title: APIClarity API Events API
  version: 1.0.0
servers:
- url: /api
tags:
- name: ApiEvents
paths:
  /apiEvents:
    get:
      parameters:
      - $ref: '#/components/parameters/startTime'
      - $ref: '#/components/parameters/endTime'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/apiEventSortKey'
      - $ref: '#/components/parameters/sortDir'
      - $ref: '#/components/parameters/showNonApi'
      - $ref: '#/components/parameters/apiInfoIdIsFilter'
      - $ref: '#/components/parameters/methodIsFilter'
      - $ref: '#/components/parameters/pathIsFilter'
      - $ref: '#/components/parameters/pathIsNotFilter'
      - $ref: '#/components/parameters/pathStartsWithFilter'
      - $ref: '#/components/parameters/pathEndsWithFilter'
      - $ref: '#/components/parameters/pathContainsFilter'
      - $ref: '#/components/parameters/statusCodeIsFilter'
      - $ref: '#/components/parameters/statusCodeIsNotFilter'
      - $ref: '#/components/parameters/statusCodeGteFilter'
      - $ref: '#/components/parameters/statusCodeLteFilter'
      - $ref: '#/components/parameters/sourceIPIsFilter'
      - $ref: '#/components/parameters/sourceIPIsNotFilter'
      - $ref: '#/components/parameters/destinationIPIsFilter'
      - $ref: '#/components/parameters/destinationIPIsNotFilter'
      - $ref: '#/components/parameters/destinationPortIsFilter'
      - $ref: '#/components/parameters/destinationPortIsNotFilter'
      - $ref: '#/components/parameters/hasSpecDiffFilter'
      - $ref: '#/components/parameters/specDiffTypeIsFilter'
      - $ref: '#/components/parameters/specIsFilter'
      - $ref: '#/components/parameters/specIsNotFilter'
      - $ref: '#/components/parameters/specStartsWithFilter'
      - $ref: '#/components/parameters/specEndsWithFilter'
      - $ref: '#/components/parameters/specContainsFilter'
      - $ref: '#/components/parameters/alertIsFilter'
      - $ref: '#/components/parameters/alertIsType'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  items:
                    description: List of API events in the given time range, filters and page. List length must be lower or equal to pageSize
                    items:
                      $ref: ../common/openapi.yaml#/components/schemas/ApiEvent
                    type: array
                  total:
                    description: Total events count in the given time range and filters
                    type: integer
                required:
                - total
                type: object
          description: Success
        default:
          $ref: '#/components/responses/UnknownError'
      summary: Get API events
      tags:
      - ApiEvents
      operationId: getApiEvents
      x-operation-id-source: derived
  /apiEvents/{eventId}:
    get:
      parameters:
      - description: API event ID
        in: path
        name: eventId
        required: true
        schema:
          format: uint32
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ../common/openapi.yaml#/components/schemas/ApiEvent
          description: Success
        default:
          $ref: '#/components/responses/UnknownError'
      summary: Get API event
      tags:
      - ApiEvents
      operationId: getApiEventsByEventId
      x-operation-id-source: derived
  /apiEvents/{eventId}/providedSpecDiff:
    get:
      parameters:
      - description: API event ID
        in: path
        name: eventId
        required: true
        schema:
          format: uint32
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ../common/openapi.yaml#/components/schemas/ApiEventSpecDiff
          description: Success
        default:
          $ref: '#/components/responses/UnknownError'
      summary: Get API event provided spec diff
      tags:
      - ApiEvents
      operationId: getApiEventsByEventIdProvidedSpecDiff
      x-operation-id-source: derived
  /apiEvents/{eventId}/reconstructedSpecDiff:
    get:
      parameters:
      - description: API event ID
        in: path
        name: eventId
        required: true
        schema:
          format: uint32
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ../common/openapi.yaml#/components/schemas/ApiEventSpecDiff
          description: Success
        default:
          $ref: '#/components/responses/UnknownError'
      summary: Get API event reconstructed spec diff
      tags:
      - ApiEvents
      operationId: getApiEventsByEventIdReconstructedSpecDiff
      x-operation-id-source: derived
components:
  parameters:
    pathIsFilter:
      in: query
      name: path[is]
      schema:
        items:
          type: string
        type: array
    pathContainsFilter:
      in: query
      name: path[contains]
      schema:
        items:
          type: string
        type: array
    methodIsFilter:
      in: query
      name: method[is]
      schema:
        items:
          $ref: ../common/openapi.yaml#/components/schemas/HttpMethod
        type: array
    alertIsType:
      in: query
      name: alertType[is]
      schema:
        items:
          type: string
        type: array
    sourceIPIsNotFilter:
      in: query
      name: sourceIP[isNot]
      schema:
        items:
          type: string
        type: array
    page:
      description: Page number of the query
      in: query
      name: page
      required: true
      schema:
        type: integer
    specDiffTypeIsFilter:
      in: query
      name: specDiffType[is]
      schema:
        items:
          $ref: ../common/openapi.yaml#/components/schemas/DiffType
        type: array
    specStartsWithFilter:
      in: query
      name: spec[start]
      schema:
        type: string
    startTime:
      description: Start time of the query
      in: query
      name: startTime
      required: true
      schema:
        format: date-time
        type: string
    pathStartsWithFilter:
      in: query
      name: path[start]
      schema:
        type: string
    apiInfoIdIsFilter:
      in: query
      name: apiInfoId[is]
      schema:
        format: uint32
        type: integer
    sortDir:
      description: Sorting direction
      in: query
      name: sortDir
      schema:
        default: ASC
        enum:
        - ASC
        - DESC
        type: string
    pageSize:
      description: Maximum items to return
      in: query
      name: pageSize
      required: true
      schema:
        maximum: 50
        minimum: 1
        type: integer
    statusCodeIsFilter:
      in: query
      name: statusCode[is]
      schema:
        items:
          type: string
        type: array
    destinationPortIsNotFilter:
      in: query
      name: destinationPort[isNot]
      schema:
        items:
          type: string
        type: array
    destinationIPIsNotFilter:
      in: query
      name: destinationIP[isNot]
      schema:
        items:
          type: string
        type: array
    specIsNotFilter:
      in: query
      name: spec[isNot]
      schema:
        items:
          type: string
        type: array
    statusCodeLteFilter:
      description: less than or equal
      in: query
      name: statusCode[lte]
      schema:
        type: string
    statusCodeGteFilter:
      description: greater than or equal
      in: query
      name: statusCode[gte]
      schema:
        type: string
    apiEventSortKey:
      description: Sort key
      in: query
      name: sortKey
      required: true
      schema:
        $ref: ../common/openapi.yaml#/components/schemas/ApiEventSortKey
    destinationPortIsFilter:
      in: query
      name: destinationPort[is]
      schema:
        items:
          type: string
        type: array
    specIsFilter:
      in: query
      name: spec[is]
      schema:
        items:
          type: string
        type: array
    statusCodeIsNotFilter:
      in: query
      name: statusCode[isNot]
      schema:
        items:
          type: string
        type: array
    pathEndsWithFilter:
      in: query
      name: path[end]
      schema:
        type: string
    sourceIPIsFilter:
      in: query
      name: sourceIP[is]
      schema:
        items:
          type: string
        type: array
    destinationIPIsFilter:
      in: query
      name: destinationIP[is]
      schema:
        items:
          type: string
        type: array
    hasSpecDiffFilter:
      in: query
      name: hasSpecDiff[is]
      schema:
        type: boolean
    specContainsFilter:
      in: query
      name: spec[contains]
      schema:
        items:
          type: string
        type: array
    endTime:
      description: End time of the query
      in: query
      name: endTime
      required: true
      schema:
        format: date-time
        type: string
    pathIsNotFilter:
      in: query
      name: path[isNot]
      schema:
        items:
          type: string
        type: array
    alertIsFilter:
      description: Alert Kind [ALERT_INFO or ALERT_WARN]
      in: query
      name: alert[is]
      schema:
        items:
          $ref: ../common/openapi.yaml#/components/schemas/AlertSeverityEnum
        type: array
    specEndsWithFilter:
      in: query
      name: spec[end]
      schema:
        type: string
    showNonApi:
      in: query
      name: showNonApi
      required: true
      schema:
        type: boolean
  responses:
    UnknownError:
      content:
        application/json:
          schema:
            $ref: ../common/openapi.yaml#/components/schemas/ApiResponse
      description: unknown error
