openapi: 3.2.0
info:
  title: APIClarity Trace Analyzer Module Event Annotations API
  version: 0.0.1
  description: APIClarity Trace Analyzer Module API
tags:
- name: EventAnnotations
paths:
  /eventAnnotations/{eventID}:
    get:
      operationId: GetEventAnnotations
      summary: Get Annotations for an event
      description: Get Trace Analyzer Annotations for a specific event
      parameters:
      - name: eventID
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - $ref: '#/components/parameters/redacted'
      responses:
        '200':
          description: Annotation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotations'
      tags:
      - EventAnnotations
components:
  schemas:
    Annotations:
      type: object
      required:
      - total
      properties:
        total:
          type: integer
          description: Total event annotations count
        items:
          type: array
          items:
            $ref: '#/components/schemas/Annotation'
    Annotation:
      type: object
      properties:
        name:
          type: string
        annotation:
          type: string
        severity:
          type: string
        kind:
          type: string
      required:
      - id
      - name
      - annotation
      - severity
      - kind
  parameters:
    redacted:
      name: redacted
      in: query
      required: false
      schema:
        default: false
        type: boolean
