openapi: 3.2.0
info:
  title: APIClarity Features API
  version: 1.0.0
servers:
- url: /api
tags:
- name: Features
paths:
  /features:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClarityFeatureList'
          description: Success
      summary: Get the list of APIClarity features and for each feature the list of API hosts…
      tags:
      - Features
      operationId: getFeatures
      x-operation-id-source: derived
components:
  schemas:
    APIClarityFeatureEnum:
      description: APIClarity Feature Name
      enum:
      - bfla
      - fuzzer
      - spec_differ
      - specdiffs
      - specreconstructor
      - specreconstructor
      - traceanalyzer
      type: string
    APIClarityFeatureList:
      description: List of APIClarity features and for each feature the list of API hosts (Group by trace sources, in the form 'host:port') the feature requires to get trace for
      properties:
        features:
          items:
            $ref: '#/components/schemas/APIClarityFeature'
          type: array
      type: object
    HostsToTraceForTraceSource:
      description: list of API hosts (in the form 'host:port') managed by a traceSource
      properties:
        hostsToTrace:
          description: List of hosts (in the form 'host:port')
          items:
            type: string
          type: array
        traceSourceID:
          description: ID of the trace source
          format: uint32
          type: integer
      type: object
    APIClarityFeature:
      description: Description of APIClarity feature and the list of API hosts (Group by trace sources, in the form 'host:port') the feature requires to get trace for
      properties:
        featureDescription:
          description: Short human readable description of the feature
          type: string
        featureName:
          $ref: '#/components/schemas/APIClarityFeatureEnum'
        hostsToTrace:
          $ref: '#/components/schemas/HostsToTraceForComponent'
      required:
      - featureName
      type: object
    HostsToTraceForComponent:
      description: List of trace sources for a component, with theirs list of API hosts to get trace for
      properties:
        component:
          description: Component name
          type: string
        traceSourcesHosts:
          items:
            $ref: '#/components/schemas/HostsToTraceForTraceSource'
          type: array
      type: object
